shopp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls)
]


urlpatterns +=i18n_patterns(
    path('', include('fact_app.urls')),

)



if settings.DEBUG :
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fact_app/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils.translation import  gettext_lazy as _

class Customer(models.Model):
    SEX_TYPE= (
        ('M',('Male')),
        ('F', ('Feminine')) ,
    )
    name = models.CharField(max_length=132)
    email = models.EmailField()
    phone = models.CharField(max_length=132)
    address = models.CharField(max_length=132)
    sex =models.CharField(max_length=1,choices=SEX_TYPE)
    age = models.CharField(max_length=12)
    city = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=15)
    create_date = models.DateTimeField(auto_now_add=True)
    save_by= models.ForeignKey(User, on_delete=models.PROTECT)


    class Meta :
        verbose_name = "Customer"
        verbose_name_plural = "Customers"


    def __str__(self):
        return  self.name


class Invoice(models.Model):



    INVOICE_TYPE = (

        ('R', ('RECEIPT')),
        ('P',('PROFORMA INVOICE')),
        ('I',('INVOICE')),

    )

    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    save_by = models.ForeignKey(User,on_delete=models.PROTECT)
    invoice_date_time =  models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=1000,decimal_places=2)
    last_updated_date = models.DateTimeField(null=True,blank=True)
    paid = models.BooleanField(default=False)
    invoice_type = models.CharField(max_length=1,choices=INVOICE_TYPE)
    comment = models.TextField(null=True,max_length=1000,blank=True)

    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"


    def __str__(self):

        return  f"{self.customer.name}_{self.invoice_date_time}"

    @property

    def get_total(self):

        articles = self.article_set.all()

        total = sum(article.get_total for article in  articles)
        return total



class Article(models.Model):

    invoice = models.ForeignKey(Invoice,on_delete=models.CASCADE)
    name = models.CharField(max_length=132)
    quantity  = models.IntegerField()
    unit_price = models.DecimalField(max_digits=1000,decimal_places=2)
    total = models.DecimalField(max_digits=1000,decimal_places=2)


    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'


    @property

    def get_total(self):
        total = self.quantity * self.unit_price
        return total

templates/add_customer.html
{% extends  "base.html" %}


{% block content %}


<br> <br><br><br>
<h1 class="text-capitalize text-center mx-10 bg-dark text white">
    Register a new customer

</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="name">Name</label>
            <input name="name" required type="text" class="form-control" id="name" placeholder="customer first and last name">
        </div>

         <div class="form-group col-md-4">
            <label for="email">Email</label>
            <input name="email" required type="email" class="form-control" id="email" placeholder="customer email">
        </div>

         <div class="form-group col-md-2">
            <label for="phone">Phone</label>
            <input name="phone" required type="number" class="form-control" id="phone" placeholder="customer phone">
        </div>

    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="sex">Sex</label>
            <select name="sex" class="form-control" required id="sex">
                <option choose the gender ...></option>
                <option value="M">Male</option>
                <option value="F">Feminine</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            <label for="age">Age</label>
            <select name="age" class="form-control" required id="age">
                <option choose the age range ...></option>
                <option value="15-25">15-25</option>
                <option value="25-35">25-35</option>
                <option value="35-55">35-55</option>
            </select>
        </div>
  </div>
    <div class="form-row">
         <div class="form-group col-md-6">
                <label for="city">City</label>
                <input name="city" required type="text" class="form-control" id="city" placeholder="customer city">
            </div>

         <div class="form-group col-md-6">
                <label for="zip_code">Zip code</label>
                <input name="zip_code" required type="text" class="form-control" id="zip_code" placeholder="customer zip_code">
            </div>
  </div>


         <div class="form-row">
            <div class="form-group col-md-12 ">
                <label for="address">Address</label>
                <input name="address" type="text" required class="form-control" id="address" placeholder="Customer address">
            </div>
        </div>


    </div>







    <button type="submit" class="btn btn-primary">Save</button>
    <br><br><br>
</form>



{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}





{% block content %}
<br><br>

<div class="row">
   <a href="{% url 'add-invoice'%}" class="btn col-md-4 btn-primary">
      {% trans 'Register a new invoice' %} <span class="badge text-bg-secondary"></span>
   </a>

   <a href='#' class="col-md-4">
      <span class="badge text-bg-secondary"></span>
   </a>

   <a href="{% url 'add-customer' %}" class="btn col-md-4 btn-primary">
    Register a new customer <span class="badge text-bg-secondary"></span>
   </a>

</div>

<br> <br>

<div class="form-group ">
   <input id="search" class="form-control" type="text" placeholder="Search....">
</div>

<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">CUSTOMERS NAME</th>
            <th scope="col">DATE</th>
            <th scope="col">TOTAL</th>
            <th scope="col">PAID</th>
            <th scope="col">TYPE OF INVOICE</th>
            <th scope="col">ACTION</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if invoices %}
         {% for facture in invoices %}
         <tr>
            <th scope="row">{{ facture.pk }}</th>
            <td>{{facture.customer.name}}</td>
            <td>{{facture.invoice_date_time}}</td>
            <td>{{ facture.get_total }}</td>
            <td>
               {% if facture.paid %}
               <img src="{% static 'images/icon-yes.svg' %}" alt="True">
               {% else %}
               <img src="{% static 'images/icon-no.svg' %}" alt="False">
               {% endif %}
            </td>
            <td>{{ facture.get_invoice_type_display }}</td>
            <td>
               <a href=" {% url 'view-invoice' pk=facture.pk  %}" title="Detail" class="badge text-white bg-success">{% trans 'View' %}</a>

               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                  class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}"
                  data-customer="{{facture.customer.name}}">{% trans 'Delete' %}
               </button>

               <button id="btn-invoice-mod" type="button" data-toggle="modal" title="Modifier" data-target="#modifier"
                  data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                  class="badge text-dark bg-warning">{% trans 'Modify' %}
               </button>
            </td>
         </tr>

         {% endfor %}


         {% if invoices.has_other_pages %}

         <div class="btn-group" role="group" aria-label="Item pagination">

            {% if invoices.has_previous %}

            <a href="?page={{ invoices.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>

            {% endif %}

            {% for page_number in invoices.paginator.page_range %}

               {% if invoices.number == page_number %}

                  <button class="btn btn-outline-primary active">
                     <span> {{page_number}} <span class="sr-only">(current)</span></span>

                  </button>

                  {% else %}
                     <a href="?page={{page_number}}" class="btn btn-outline-primary">
                        {{ page_number }}
                     </a>


               {% endif %}

            {% endfor %}

            {% if invoices.has_next %}

               <a href="?page={{ invoices.next_page_number }}" class="btn btn-outline-primary">&laquo;</a>

            {% endif %}



         </div>

         {% endif %}

         {% else %}

         <p class="text-center text-white">No invoice found.</p>
         {% endif %}


      </tbody>

   </table>
</div>

<!-- Modal modifier -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modification</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">

               <input name="id_modified" type="hidden" id="id_modified">

               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id"> This bill has been paid?</strong></label>

               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">Yes</label>

               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">No</label><br>

            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-primary">Save</button>
            </div>
         </form>
      </div>
   </div>
</div>
<!-- end modal-->

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Delete Invoice</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Are you sure you want to delete the invoice  ?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
               </div>
            </form>
         </div>

      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">

   // modification

   $(document).on('click', '#btn-invoice-mod', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);

   })

   // deleting of invoice

   $(document).on('click', '#btn-invoice-sup', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);

   })





</script>


<script>

   $(document).ready(function(){
      $("#search").on("keyup", function(){
         var value = $(this).val().toLowerCase();
         $("#myTable tr").filter(function(){
            $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value)>-1)
         });
      });
   });

</script>



{% endblock %}

templates/invoice-pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- jquery-->

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>


    <title>Facture</title>

	<style>
		body{
    margin: 0;
    padding: 0;
    font: 400 .875rem 'Open Sans', sans-serif;
    color: #bcd0f7;
    background: #1A233A;
    position: relative;
    height: 100%;
}
.invoice-container {
    padding: 1rem;
}
.invoice-container .invoice-header .invoice-logo {
    margin: 0.8rem 0 0 0;
    display: inline-block;
    font-size: 1.6rem;
    font-weight: 700;
    color: #bcd0f7;
}
.invoice-container .invoice-header .invoice-logo img {
    max-width: 130px;
}
.invoice-container .invoice-header address {
    font-size: 0.8rem;
    color: #8a99b5;
    margin: 0;
}
.invoice-container .invoice-details {
    margin: 1rem 0 0 0;
    padding: 1rem;
    line-height: 180%;
    background: #1a233a;
}
.invoice-container .invoice-details .invoice-num {
    text-align: right;
    font-size: 0.8rem;
}
.invoice-container .invoice-body {
    padding: 1rem 0 0 0;
}
.invoice-container .invoice-footer {
    text-align: center;
    font-size: 0.7rem;
    margin: 5px 0 0 0;
}

.invoice-status {
    text-align: center;
    padding: 1rem;
    background: #272e48;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    margin-bottom: 1rem;
}
.invoice-status h2.status {
    margin: 0 0 0.8rem 0;
}
.invoice-status h5.status-title {
    margin: 0 0 0.8rem 0;
    color: #8a99b5;
}
.invoice-status p.status-type {
    margin: 0.5rem 0 0 0;
    padding: 0;
    line-height: 150%;
}
.invoice-status i {
    font-size: 1.5rem;
    margin: 0 0 1rem 0;
    display: inline-block;
    padding: 1rem;
    background: #1a233a;
    -webkit-border-radius: 50px;
    -moz-border-radius: 50px;
    border-radius: 50px;
}
.invoice-status .badge {
    text-transform: uppercase;
}

@media (max-width: 767px) {
    .invoice-container {
        padding: 1rem;
    }
}

.card {
    background: #272E48;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    border: 0;
    margin-bottom: 1rem;
}

.custom-table {
    border: 1px solid #2b3958;
}
.custom-table thead {
    background: #2f71c1;
}
.custom-table thead th {
    border: 0;
    color: #ffffff;
}
.custom-table > tbody tr:hover {
    background: #172033;
}
.custom-table > tbody tr:nth-of-type(even) {
    background-color: #1a243a;
}
.custom-table > tbody td {
    border: 1px solid #2e3d5f;
}

.table {
    background: #1a243a;
    color: #bcd0f7;
    font-size: .75rem;
}
.text-success {
    color: #c0d64a !important;
}
.custom-actions-btns {
    margin: auto;
    display: flex;
    justify-content: flex-end;
}
.custom-actions-btns .btn {
    margin: .3rem 0 .3rem .3rem;
}


	</style>
</head>
<body>


    <div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="donaldprogrammeur.com" class="invoice-logo">
    									Entreprise Wato
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Merveilleux Guiradoumadji Inc, 45 NorthWest<br>
    									<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date_time}}</div>
    									</div>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-body">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}

    											<tr>



                                                    <td>
    													{{ article.name }}

    												</td>

													<td>
    													{{ article.id }}

    												</td>

													<td>
    													{{ article.quantity }}

    												</td>

													<td>
    													{{ article.unit_price }}

    												</td>

													<td>
    													{{ article.get_total }}

    												</td>



    											</tr>
                                               {% endfor %}


    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td>
                                                            PAID:

                                                        {% if obj.paid  %}

                                                          <stron style="color: green;"> YES</stron>
                                                        {% else %}
                                                           <stron style="color: red ; "> NO</stron>
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-footer">
    						Thank you for your purchase {{date}}.
    					</div>

    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>



</body>
</html>

templates/invoice-template.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="donaldprogrammeur.com" class="invoice-logo">
    									Donald Programmer
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Donald Programmer Inc, 45 NorthWest<br>
    									Cameroon, Douala<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}, Cameroon
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date}}</div>
    									</div>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-body">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}

    											<tr>



                                                    <td>
    													{{ article.name }}

    												</td>

													<td>
    													{{ article.id }}

    												</td>

													<td>
    													{{ article.quantite }}

    												</td>

													<td>
    													{{ article.prix_u }}

    												</td>

													<td>
    													{{ article.get_total }}

    												</td>



    											</tr>
                                               {% endfor %}


    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td>
                                                            PAID:

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'images/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'images/icon-no.svg' %}" alt="False">

                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-footer">
    						Thank you for your purchases .
    					</div>

    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}

templates/invoice.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="{% url 'invoice-pdf' pk=obj.pk %}" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="/" class="invoice-logo">
    									Entreprise Wato
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Merveilleux Guiradoumadji Inc, 45 NorthWest<br>
    									<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date_time}}</div>
    									</div>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-body">

    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}

    											<tr>



                                                    <td>
    													{{ article.name }}

    												</td>

													<td>
    													{{ article.id }}

    												</td>

													<td>
    													{{ article.quantity }}

    												</td>

													<td>
    													{{ article.unit_price }}

    												</td>

													<td>
    													{{ article.get_total }}

    												</td>



    											</tr>
                                               {% endfor %}


    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td>
                                                            PAID:

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'images/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'images/icon-no.svg' %}" alt="False">

                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->

    					</div>

    					<div class="invoice-footer">
    						Thank you for your purchase.
    					</div>

    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}